resources:
  - name: github_demo
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub
      branches:
        include: master
  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: pipeline_demo
    steps:          
      - name: bash_demo
        type: Bash
        configuration:
          inputResources:
            - name: github_demo
        execution:
          onExecute:
            - echo "executing bash step bash_demo..."
      - name: bash_demo_8
        type: Bash
        configuration:
          inputResources:
            - name: github_demo
          inputSteps:
            - name: bash_demo
          outputResources:
            - name: propertyBag
        execution:
          onExecute:
            - echo "executing bash step bash_demo_1..."
